spring:

  sql:
    init:
      mode: always

  datasource:
    url: jdbc:postgresql://localhost:5439/crypto_currency_watcher_data
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20

  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none

  server.servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

available-cryptocurrency:
  availableCryptocurrencies:
    - id: 90
      symbol: BTC
    - id: 80
      symbol: ETH
    - id: 48543
      symbol: SOL

logging:
  level:
    root: info
    com.cryptocurrencywatcher: debug
  file:
    name: logs/application.log

server:
  port: 8095